// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9uL-CZr5hcLwX-3FsxrWF85VsCIlr4E',
    appId: '1:284532386410:android:db0fad336e015ad8197813',
    messagingSenderId: '284532386410',
    projectId: 'math-learning-app-a5262',
    storageBucket: 'math-learning-app-a5262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2oqkbcMmInKxgemxn_wYPTN6ArLda7k',
    appId: '1:284532386410:ios:0c8edc42c8d1b713197813',
    messagingSenderId: '284532386410',
    projectId: 'math-learning-app-a5262',
    storageBucket: 'math-learning-app-a5262.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NGYggOaGN0swD5kxvlJX3rI-mzjjilk',
    appId: '1:284532386410:web:a390230595098d5c197813',
    messagingSenderId: '284532386410',
    projectId: 'math-learning-app-a5262',
    authDomain: 'math-learning-app-a5262.firebaseapp.com',
    storageBucket: 'math-learning-app-a5262.firebasestorage.app',
    measurementId: 'G-216DYT9658',
  );

}